2017-03-14 22:00:02,959 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-14 22:00:02,962 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-14 22:00:03,004 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-14 22:00:03,004 INFO      Action ID: 1, "delete_indices" completed.
2017-03-14 22:00:03,004 INFO      Job completed.
2017-03-15 22:00:02,686 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-15 22:00:02,690 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-15 22:00:02,741 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-15 22:00:02,741 INFO      Action ID: 1, "delete_indices" completed.
2017-03-15 22:00:02,741 INFO      Job completed.
2017-03-16 22:00:02,656 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-16 22:00:02,660 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-16 22:00:02,706 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-16 22:00:02,706 INFO      Action ID: 1, "delete_indices" completed.
2017-03-16 22:00:02,706 INFO      Job completed.
2017-03-17 22:00:02,764 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-17 22:00:02,768 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-17 22:00:02,806 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-17 22:00:02,806 INFO      Action ID: 1, "delete_indices" completed.
2017-03-17 22:00:02,806 INFO      Job completed.
2017-03-18 22:00:02,903 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-18 22:00:02,907 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-18 22:00:02,944 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-18 22:00:02,944 INFO      Action ID: 1, "delete_indices" completed.
2017-03-18 22:00:02,945 INFO      Job completed.
2017-03-19 22:00:02,933 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-19 22:00:02,936 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-19 22:00:02,981 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-19 22:00:02,981 INFO      Action ID: 1, "delete_indices" completed.
2017-03-19 22:00:02,982 INFO      Job completed.
2017-03-20 22:00:02,884 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-20 22:00:02,887 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-20 22:00:02,930 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-20 22:00:02,930 INFO      Action ID: 1, "delete_indices" completed.
2017-03-20 22:00:02,930 INFO      Job completed.
2017-03-21 22:00:02,732 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x3ca93d0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x3ca93d0>: Failed to establish a new connection: [Errno 111] Connection refused)
2017-03-22 22:00:02,829 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-22 22:00:02,841 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-22 22:00:02,888 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-22 22:00:02,888 INFO      Action ID: 1, "delete_indices" completed.
2017-03-22 22:00:02,888 INFO      Job completed.
2017-03-23 22:00:02,298 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-23 22:00:02,305 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-23 22:00:02,360 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2017-03-23 22:00:02,360 INFO      Action ID: 1, "delete_indices" completed.
2017-03-23 22:00:02,360 INFO      Job completed.
2017-03-24 22:00:03,079 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-24 22:00:03,083 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-24 22:00:03,124 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-03-25 22:00:02,703 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x30973d0>: Failed to establish a new connection: [Errno 113] No route to host) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x30973d0>: Failed to establish a new connection: [Errno 113] No route to host)
2017-03-26 22:00:02,662 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x3bab3d0>: Failed to establish a new connection: [Errno 113] No route to host) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x3bab3d0>: Failed to establish a new connection: [Errno 113] No route to host)
2017-03-27 22:00:02,870 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-27 22:00:05,886 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-27 22:00:05,946 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-03-28 22:00:02,963 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-28 22:00:05,977 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-28 22:00:06,019 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-03-29 22:00:02,893 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-29 22:00:02,900 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-29 22:00:02,941 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-03-30 22:00:02,820 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-30 22:00:02,826 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-30 22:00:05,870 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-03-31 22:00:02,696 INFO      Preparing Action ID: 1, "delete_indices"
2017-03-31 22:00:02,702 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-03-31 22:00:05,752 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-04-01 22:00:02,619 INFO      Preparing Action ID: 1, "delete_indices"
2017-04-01 22:00:02,624 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-04-01 22:00:02,661 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-04-02 22:00:02,728 INFO      Preparing Action ID: 1, "delete_indices"
2017-04-02 22:00:02,733 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-04-02 22:00:05,775 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-04-03 22:00:02,806 INFO      Preparing Action ID: 1, "delete_indices"
2017-04-03 22:00:02,811 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-04-03 22:00:05,856 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-04-04 22:00:02,199 INFO      Preparing Action ID: 1, "delete_indices"
2017-04-04 22:00:02,203 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-04-04 22:00:02,235 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-04-05 22:00:02,247 INFO      Preparing Action ID: 1, "delete_indices"
2017-04-05 22:00:02,251 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-04-05 22:00:05,288 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-04-06 22:00:02,157 INFO      Preparing Action ID: 1, "delete_indices"
2017-04-06 22:00:02,161 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 2 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-04-06 22:00:05,198 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.AuthorizationException'>: TransportError(403, u'security_exception', u'current license is non-compliant for [security]')
2017-04-07 22:00:02,151 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x279fdd0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x279fdd0>: Failed to establish a new connection: [Errno 111] Connection refused)
2017-04-08 22:00:02,785 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x3d0fdd0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x3d0fdd0>: Failed to establish a new connection: [Errno 111] Connection refused)
2017-04-09 22:00:02,176 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x2c6ae10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x2c6ae10>: Failed to establish a new connection: [Errno 111] Connection refused)
2017-04-10 22:00:02,654 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x2227e10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x2227e10>: Failed to establish a new connection: [Errno 111] Connection refused)
2017-04-11 22:00:02,207 INFO      Preparing Action ID: 1, "delete_indices"
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x3b77810>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x3b77810>: Failed to establish a new connection: [Errno 111] Connection refused)
